runtime: nodejs20
instance_class: F1

env_variables:
  # API_KEY: "YOUR_API_KEY" # Set this in Google Cloud Console or using `gcloud app deploy --set-env-vars`


# No static handlers needed, express handles it all
# handlers:
#   - url: /.*
#     script: auto
