import React, { useEffect, useRef, useState, useCallback } from 'react';
import { InterviewSetup } from '../types';
import { useLiveInterview } from '../hooks/useLiveInterview';

interface LiveInterviewProps {
  setup: InterviewSetup;
  onEnd: () => void;
}

export function LiveInterview({ setup, onEnd }: LiveInterviewProps) {
  const { messages, isConnecting, isActive, isAgentSpeaking, error, micLevel, endSession, sendTextMessage, sendFeedbackRequest, isFeedbackRequested, isFeedbackComplete, feedbackTimeout } = useLiveInterview(setup);
  const [showExitModal, setShowExitModal] = useState(false);
  const [inputText, setInputText] = useState('');
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    // Small delay to ensure the DOM has updated with the new message
    const timeoutId = setTimeout(scrollToBottom, 50);
    return () => clearTimeout(timeoutId);
  }, [messages]);

  // Handle browser close warning
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isActive && messages.length > 0 && !showExitModal) {
        e.preventDefault();
        e.returnValue = '';
      }
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isActive, messages, showExitModal]);

  const downloadTranscript = useCallback(() => {
    if (messages.length === 0) return;

    const dateStr = new Date().toLocaleDateString();
    const timeStr = new Date().toLocaleTimeString();
    
    let reportText = `===========================================================
     INTERVIEW MASTER: FULL SESSION REPORT
===========================================================
Date: ${dateStr}
Time: ${timeStr}
Role Context: ${setup.jdUrl || 'Custom Description'}
${'='.repeat(59)}\n\n`;

    reportText += `--- CONVERSATION LOG ---\n\n`;

    messages.forEach((m, idx) => {
      const msgTime = new Date(m.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      const role = m.role === 'user' ? 'CANDIDATE' : 'INTERVIEWER';
      
      // Determine if this is the final feedback message
      const isLastMessage = idx === messages.length - 1;
      const isFeedback = isLastMessage && m.role === 'model' && isFeedbackRequested;

      if (isFeedback) {
        reportText += `\n${'='.repeat(59)}\n`;
        reportText += `⭐ FINAL AI EVALUATION & FEEDBACK ⭐\n`;
        reportText += `${'='.repeat(59)}\n\n`;
        reportText += `${m.text}\n\n`;
      } else {
        reportText += `[${msgTime}] ${role}:\n${m.text}\n\n`;
      }
    });

    reportText += `\n${'='.repeat(59)}\n`;
    reportText += `End of Report - Generated by Interview Master AI\n`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Interview_Full_Report_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [messages, setup, isFeedbackRequested]);

  const handleSendMessage = (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!inputText.trim() || !isActive || isFeedbackRequested) return;
    
    sendTextMessage(inputText.trim());
    setInputText('');
  };

  const handleEndSessionClick = () => {
    // Only show modal, don't end session yet
    setShowExitModal(true);
  };

  const confirmEndSession = (getFeedback: boolean) => {
    if (getFeedback) {
        setShowExitModal(false);
        if (sendFeedbackRequest) {
            sendFeedbackRequest();
        }
    } else {
        endSession();
        onEnd();
    }
  };
  
  const handleFinalExit = () => {
      setShowExitModal(false);
      onEnd();
  }

  if (error && messages.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-12 text-center space-y-4">
        <div className="text-red-500 text-5xl mb-4">⚠️</div>
        <h3 className="text-2xl font-bold">Session Error</h3>
        <p className="text-slate-400 max-w-md">{error}</p>
        <button onClick={onEnd} className="bg-slate-700 px-6 py-2 rounded-lg hover:bg-slate-600 transition-colors">Go Back</button>
      </div>
    );
  }

  return (
    <div className="w-full max-w-6xl flex flex-col h-[calc(100vh-12rem)] relative bg-slate-800/20 md:bg-slate-800/30 rounded-3xl border border-slate-700/50 shadow-2xl overflow-hidden backdrop-blur-sm">
      {/* Exit Modal Overlay */}
      {showExitModal && (
        <div className="absolute inset-0 z-50 bg-slate-900/90 backdrop-blur-md flex items-center justify-center p-6 text-center animate-in fade-in duration-300">
          <div className="max-w-md w-full bg-slate-800 border border-slate-700 p-8 rounded-3xl shadow-2xl space-y-6 transform animate-in zoom-in-95 duration-300">
            <div className="w-16 h-16 bg-indigo-500/10 text-indigo-400 rounded-full flex items-center justify-center mx-auto">
              <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <div>
              <h2 className="text-2xl font-bold mb-2">End Interview Session?</h2>
              <p className="text-slate-400">You can choose to get feedback from the AI before ending, or download your transcript.</p>
            </div>
            
            <div className="flex flex-col gap-3">
                <button
                    onClick={() => confirmEndSession(true)}
                    className="w-full py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl transition-all shadow-lg shadow-indigo-500/20 flex items-center justify-center gap-2"
                >
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    End & Get Feedback
                </button>
                
                <button
                    onClick={downloadTranscript}
                    className="w-full py-3 bg-slate-700 hover:bg-slate-600 text-slate-100 font-semibold rounded-xl transition-all flex items-center justify-center gap-2"
                >
                    <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Download Full Report
                </button>

                <div className="grid grid-cols-2 gap-3 mt-2">
                    <button
                        onClick={() => setShowExitModal(false)}
                        className="py-3 bg-slate-800 border border-slate-600 hover:bg-slate-700 text-slate-300 font-medium rounded-xl transition-all"
                    >
                        Cancel
                    </button>
                    <button
                        onClick={() => confirmEndSession(false)}
                        className="py-3 bg-red-500/10 border border-red-500/20 hover:bg-red-500/20 text-red-400 font-medium rounded-xl transition-all"
                    >
                        Exit Now
                    </button>
                </div>
            </div>
          </div>
        </div>
      )}

      {/* Status Bar */}
      <div className="px-6 py-3 bg-slate-900/50 flex items-center justify-between border-b border-slate-700">
        <div className="flex items-center gap-3">
          <div className={`w-3 h-3 rounded-full ${isActive ? 'bg-green-500 animate-pulse' : 'bg-slate-500'}`}></div>
          <span className="text-sm font-medium text-slate-300">
            {isConnecting ? 'Initializing Interviewer...' : isActive ? 'Session Live' : 'Session Ended'}
          </span>
        </div>
        <button
            onClick={isFeedbackComplete ? handleFinalExit : isFeedbackRequested ? () => confirmEndSession(false) : handleEndSessionClick}
            disabled={!isActive || showExitModal}
            className={`px-4 py-1.5 text-xs font-semibold rounded-full transition-all shadow-sm ${
              isFeedbackRequested 
                ? 'bg-indigo-600 text-white hover:bg-indigo-700 ring-2 ring-indigo-500/20' 
                : 'text-red-400 bg-red-500/10 border border-red-500/20 hover:bg-red-500/20'
            } disabled:opacity-50 disabled:pointer-events-none`}
        >
            {isFeedbackComplete ? 'Finish & Exit' : isFeedbackRequested ? 'End Session Early' : 'End Session'}
        </button>
      </div>

      <div className="flex-1 flex flex-row overflow-hidden">
        {/* Agent Panel (Sidebar) */}
        {!isConnecting && (
          <div className="hidden md:flex w-80 flex-shrink-0 bg-slate-900/30 border-r border-slate-700/50 p-6 flex-col items-center justify-center space-y-8">
            <div className="relative">
              <div className={`w-32 h-32 rounded-full flex items-center justify-center transition-all duration-500 ${isAgentSpeaking ? 'ring-8 ring-indigo-500/20 bg-indigo-500/10' : 'bg-slate-800'}`}>
                {isAgentSpeaking ? (
                  <div className="flex items-end gap-1.5 h-12">
                    {[...Array(5)].map((_, i) => (
                      <div 
                        key={i} 
                        className="w-1.5 bg-indigo-400 rounded-full animate-bounce"
                        style={{ 
                          height: '24px',
                          animationDelay: `${i * 0.1}s`,
                          animationDuration: '0.6s'
                        }}
                      />
                    ))}
                  </div>
                ) : (
                  <svg className="w-16 h-16 text-slate-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
                  </svg>
                )}
              </div>
              <div className="absolute -bottom-2 -right-2 bg-indigo-600 p-2 rounded-lg shadow-xl">
                 <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                   <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                 </svg>
              </div>
            </div>
            <div className="text-center space-y-4">
              <div className="space-y-1">
                <h4 className="font-bold text-slate-200">AI Interviewer</h4>
                <p className="text-xs text-slate-500 uppercase tracking-widest font-semibold">
                  {isFeedbackComplete ? 'Evaluation Complete' : isFeedbackRequested ? 'Reviewing Performance' : isAgentSpeaking ? 'Speaking...' : 'Listening...'}
                </p>
              </div>

              {/* User Mic Visualizer - Hide when feedback requested */}
              {!isFeedbackRequested && (
                <div className="pt-4 border-t border-slate-700/50 flex flex-col items-center gap-3">
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">
                      Your Microphone
                  </span>
                  <div className="flex items-end gap-1 h-6 text-green-400">
                    {[...Array(12)].map((_, i) => {
                      const threshold = i * 4; 
                      const isActive = micLevel > threshold;
                      const height = isActive ? Math.min(20, (micLevel / 12) + Math.random() * 8) : 3;
                      return (
                        <div 
                          key={i} 
                          className={`w-1 rounded-full transition-all duration-75 ${isActive ? 'bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.4)]' : 'bg-slate-700/50'}`}
                          style={{ height: `${height}px` }}
                        />
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        <div className="flex-1 flex flex-col p-4 md:p-6 overflow-hidden">
          {isConnecting ? (
            <div className="flex-1 flex flex-col items-center justify-center text-center space-y-6">
              <div className="relative">
                <div className="w-24 h-24 border-4 border-indigo-500/30 border-t-indigo-500 rounded-full animate-spin"></div>
                <div className="absolute inset-0 flex items-center justify-center">
                  <svg className="w-10 h-10 text-indigo-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </div>
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-semibold">Reviewing Documents</h3>
                <p className="text-slate-500 text-sm">The agent is analyzing the job description and your resume.</p>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col min-h-0 relative">
              {/* Feedback Status Banner */}
              {isFeedbackRequested && (
                <div className={`absolute top-0 inset-x-0 z-10 p-3 backdrop-blur-md border-b flex items-center justify-center gap-3 animate-in slide-in-from-top duration-300 ${
                  feedbackTimeout 
                    ? 'bg-red-600/90 border-red-400/30' 
                    : isFeedbackComplete 
                      ? 'bg-green-600/90 border-green-400/30'
                      : 'bg-indigo-600/90 border-indigo-400/30'
                }`}>
                   {!feedbackTimeout && !isFeedbackComplete && (
                     <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                   )}
                   <span className="text-xs font-bold text-white uppercase tracking-wider">
                      {feedbackTimeout 
                        ? '⏱️ Feedback timeout - Please try again' 
                        : isFeedbackComplete 
                          ? '✅ Evaluation Complete' 
                          : '📝 Interviewer is producing feedback...'}
                   </span>
                </div>
              )}
              
              <div ref={scrollContainerRef} className={`flex-1 overflow-x-hidden pr-2 space-y-6 scrollbar-always-y scroll-smooth ${isFeedbackRequested ? 'pt-14' : ''}`}>
                {messages.length === 0 && (
                  <div className="h-full flex flex-col items-center justify-center text-center text-slate-500 space-y-4">
                    <div className="p-4 bg-slate-700/30 rounded-full">
                      <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
                      </svg>
                    </div>
                    <p>
                      {isActive 
                          ? <>Speak clearly into your microphone.<br/>The agent will respond in real-time.</>
                          : 'The interview has ended.'
                      }
                    </p>
                  </div>
                )}
                {messages.map((msg, idx) => (
                  <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} animate-in fade-in slide-in-from-bottom-2 duration-300`}>
                    <div className={`max-w-[90%] md:max-w-[75%] rounded-2xl p-4 shadow-sm ${ 
                      msg.role === 'user' 
                        ? 'bg-indigo-600 text-white rounded-br-none' 
                        : isFeedbackRequested && idx === messages.length - 1 && msg.role === 'model'
                          ? 'bg-slate-800 border-2 border-indigo-500/50 text-slate-100 rounded-bl-none shadow-[0_0_20px_rgba(99,102,241,0.2)]'
                          : 'bg-slate-700/50 text-slate-100 border border-slate-600 rounded-bl-none'
                    }`}>
                      {isFeedbackRequested && idx === messages.length - 1 && msg.role === 'model' && (
                        <div className="flex items-center gap-2 mb-2 text-indigo-400 font-bold text-xs uppercase tracking-tighter">
                          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                          </svg>
                          Final Evaluation
                        </div>
                      )}
                      <p className="text-sm md:text-base leading-relaxed break-words whitespace-pre-wrap">{msg.text}</p>
                      <span className="text-[10px] opacity-50 mt-2 block">
                        {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                  </div>
                ))}

                {/* Save Log Prompt */}
                {isFeedbackComplete && (
                  <div className="bg-indigo-600/10 border border-indigo-500/20 rounded-2xl p-6 flex flex-col items-center gap-4 text-center animate-in zoom-in-95 duration-500 mt-8">
                    <div className="w-12 h-12 bg-indigo-600 rounded-full flex items-center justify-center text-white shadow-lg">
                      <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
                      </svg>
                    </div>
                    <div>
                      <h3 className="text-xl font-bold text-slate-100">AI Evaluation Ready</h3>
                      <p className="text-slate-400 text-sm">Download your comprehensive report including the full conversation transcript and structured AI feedback.</p>
                      <div className="mt-3 flex items-center justify-center gap-4 text-[10px] font-bold uppercase tracking-widest text-indigo-400">
                        <span className="flex items-center gap-1"><svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg> Conversation</span>
                        <span className="flex items-center gap-1"><svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg> Evaluation</span>
                      </div>
                    </div>
                    <div className="flex gap-3 w-full max-w-sm">
                      <button
                        onClick={downloadTranscript}
                        className="flex-1 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl transition-all shadow-lg shadow-indigo-500/20"
                      >
                        Download Full Report
                      </button>
                      <button
                        onClick={handleFinalExit}
                        className="flex-1 py-3 bg-slate-800 hover:bg-slate-700 text-slate-300 font-bold rounded-xl transition-all"
                      >
                        Exit Session
                      </button>
                    </div>
                  </div>
                )}
                
                <div ref={messagesEndRef} className="h-4 w-full" />
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Mode-Specific Controls */}
      {isActive && !isConnecting && !isFeedbackRequested && (
        <div className="bg-slate-900/80 backdrop-blur-sm border-t border-slate-700">
          {setup.mode === 'voice' ? (
            <div className="h-20 px-6 py-4 flex items-center justify-center">
              <div className="flex items-center gap-4">
                <div className={`flex items-end gap-1 h-8 ${isAgentSpeaking ? 'text-indigo-400' : 'text-slate-500'}`}>
                  {[...Array(5)].map((_, i) => (
                    <div 
                      key={i} 
                      className={`w-1.5 rounded-full transition-all duration-150 ${isAgentSpeaking ? 'animate-bounce' : ''}`}
                      style={{ 
                        height: isAgentSpeaking ? `${Math.random() * 20 + 10}px` : '4px',
                        animationDelay: isAgentSpeaking ? `${i * 0.1}s` : undefined
                      }}
                    />
                  ))}
                </div>
                 <span className="text-sm font-medium text-slate-400">
                    {isAgentSpeaking ? 'Interviewer is speaking...' : 'Interviewer is listening to you...'}
                </span>
              </div>
            </div>
          ) : (
            <form onSubmit={handleSendMessage} className="p-4 flex gap-3 max-w-4xl mx-auto w-full">
              <input
                type="text"
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                placeholder="Type your response here..."
                className="flex-1 bg-slate-800 border border-slate-700 rounded-xl px-4 py-3 text-slate-100 focus:ring-2 focus:ring-indigo-500 outline-none transition-all"
                autoFocus
              />
              <button
                type="submit"
                disabled={!inputText.trim()}
                className="bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 text-white px-6 py-3 rounded-xl font-bold transition-all flex items-center gap-2 shadow-lg shadow-indigo-500/20"
              >
                Send
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                </svg>
              </button>
            </form>
          )}
        </div>
      )}
    </div>
  );
}